# Generated by Django 2.0.3 on 2018-04-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product_image',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
